import type { Metadata } from "next";
import NavigationBar from "./components/navigation-bar";

export const metadata: Metadata = {
  title: "CarsJa",
  description: "Generated by create next app",
};
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <NavigationBar/>
      {children}
    </>
  );
}
